name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install conan
      run: pip install "conan>=2.0"
    - name: Install GoogleTest
      run: |
        conan profile detect --force
        conan install . --build=missing
    - name: Build
      run: |
        cmake --preset conan-release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_TEST=ON
        cmake --build build/Release -j $(nproc)
    - name: Install Cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cppcheck cppcheck-htmlreport
    - name: Cppcheck
      run: |
        cppcheck \
          --project=./build/Release/compile_commands.json \
          --enable=all \
          --template=gcc \
          --file-filter="cstack.c" \
          --suppress=checkersReport \
          --suppress=missingIncludeSystem \
          --error-exitcode=1
    - name: Test
      run: ctest --test-dir build/Release --output-on-failure
